const data = {
    products: [
        {
            _id: '1',
            name: 'Calia Lily',
            slug: 'Calia-Lily',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p1.jpg',
            price: 24.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Peach, #6.5 pot'
        },
        {
            _id: '2',
            name: 'Begonia',
            slug: 'Begonia',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p2.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Peach, #6.0 pot'
        },
        {
            _id: '3',
            name: 'Gardenia',
            slug: 'Gardenia',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p3.jpg',
            price: 39.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Button, Bush'
        },
        {
            _id: '4',
            name: 'Dahlia',
            slug: 'Dahlia',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p4.jpg',
            price: 21.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Grande Emilio'
        },
        {
            _id: '5',
            name: 'Petunia',
            slug: 'Petunia-1',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p5.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Proven Winnersd'
        },
        {
            _id: '6',
            name: 'Lobelia',
            slug: 'Lobelia',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p6.jpg',
            price: 5.49,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Laguna Dark Blue'
        },
        {
            _id: '7',
            name: 'Petunia',
            slug: 'Petunia-2',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p7.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Velvet Hanging Basket'
        },
        {
            _id: '8',
            name: 'Petunia',
            slug: 'Petunia-3',
            category: 'Annual Flowers', categorySlug:  'Annual-Flowers',
            image: '/images/p8.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Watermelon Hanging Basket'
        },
        {
            _id: '9',
            name: 'Fern',
            slug: 'Fern',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p9.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Boston Fern Hanging Basket'
        },
        {
            _id: '10',
            name: 'Arborvitae',
            slug: 'Arborvitae',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p10.jpg',
            price: 119.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Emerald Green, 5 ft'
        },
        {
            _id: '11',
            name: 'Strawberries',
            slug: 'Strawberries',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p11.jpg',
            price: 9.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '4.25 inches, edible'
        },
        {
            _id: '12',
            name: 'Lavendar',
            slug: 'Lavendar',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p12.jpg',
            price: 119.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '#3 pot container'
        }, {
            _id: '13',
            name: 'Cherry Tomato',
            slug: 'Cherry-Tomato',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p13.jpg',
            price: 5.19,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'delightfully sweet'
        }, {
            _id: '14',
            name: 'Cucumber',
            slug: 'Cucumber',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p14.jpg',
            price: 5.19,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'crunchy pickling cucumbers'
        }, {
            _id: '15',
            name: 'Hydrangea',
            slug: 'Hydrangea',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p15.jpg',
            price: 39.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'lace-cap hydrangea and has exceptionally rich, vibrant flowers'
        },
        {
            _id: '16',
            name: 'Rose Bush', slug: 'Rose-Bush',
            slug: 'Rose-bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '17',
            name: 'Bloom Plus',
            slug: 'Bloom-Plus',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p17.jpg',
            price: 10.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Excellent for feeding all plants, indoors and outdoors.'
        },
        {
            _id: '18',
            name: 'Watering Can',
            slug: 'Watering-Can',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p18.jpg',
            price: 29.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '2.5 gallon, deep blue with two-handle design'
        },
        {
            _id: '19',
            name: 'Repel Spray',
            slug: 'Repel-Spray',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p19.jpg',
            price: 29.59,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Repels-All, Quart Ready to Spray, our favorite all natural animal repellants'
        },
        {
            _id: '20',
            name: 'Handle Tool Trowel',
            slug: 'Handle-Tool-Trowel',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p20.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Strong, lightweight tool perfect for many garden tasks.'
        },
        {
            _id: '21',
            name: 'Flower Seed Kit',
            slug: 'Flower-Seed-Kit',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/21.jpg',
            price: 9.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Wildflower Seed to attract butterflies & hummingbirds. All-in-one formula'
        },
        {
            _id: '22',
            name: 'Weed Out',
            slug: 'Weed-Out',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p22.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Weed Kiiler, quart concentrate'
        },
        {
            _id: '23',
            name: 'Soil Moist',
            slug: 'Soil-Moist',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p23.jpg',
            price: 29.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '3 lb eco-safe, water-storing polymer.  Add to soil of potted plants to reduce watering.'
        },
        {
            _id: '24',
            name: 'Hose with Nozzle',
            slug: 'Coiled-Hose-with-Nozzle',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p24.jpg',
            price: 49.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Coil spring hose protector with solid brass couplings.'
        },
        {
            _id: '25',
            name: 'Hand Trowel',
            slug: 'Hand-Trowel',
            category: 'Garden Supplies & Plant Care', categorySlug: 'Garden-Supplies-&-Plant-Care',
            image: '/images/p25.jpg',
            price: 24.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'stainless steel tool with a hardwood handle.'
        },
        {
            _id: '26',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '27',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '28',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '29',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '30',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '31',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '32',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '33',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '34',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '35',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '37',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '38',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '39',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '40',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '41',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '42',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '43',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '44',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '45',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '46',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '47',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '48',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '49',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '50',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '51',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '52',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '53',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '54',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '55',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '56',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '57',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '58',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '59',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '60',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '61',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '62',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '63',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '64',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
        {
            _id: '65',
            name: 'Rose Bush', slug: 'Rose-Bush',
            category: 'Garden Plants & Flowers', categorySlug: 'Garden-Plants-&-Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
    ],
};
export default data;