const data = {
    products: [{
            _id: '1',
            name: 'Calia Lily',
            category: 'Annual Plants',
            image: '/images/p1.jpg',
            price: 24.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Peach, #6.5 pot'
        },
        {
            _id: '2',
            name: 'Begonia',
            category: 'Annual Plants',
            image: '/images/p2.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Peach, #6.0 pot'
        },
        {
            _id: '3',
            name: 'Gardenia',
            category: 'Annual Plants',
            image: '/images/p3.jpg',
            price: 39.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Button, Bush'
        },
        {
            _id: '4',
            name: 'Dahlia',
            category: 'Annual Plants',
            image: '/images/p4.jpg',
            price: 21.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Grande Emilio'
        },
        {
            _id: '5',
            name: 'Petunia',
            category: 'Annual Plants',
            image: '/images/p5.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Purple Hanging Basket'
        },
        {
            _id: '6',
            name: 'Lobelia',
            category: 'Annual Plants',
            image: '/images/p6.jpg',
            price: 5.49,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Laguna Dark Blue'
        },
        {
            _id: '7',
            name: 'Petunia',
            category: 'Annual Plants',
            image: '/images/p7.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Velvet Hanging Basket'
        },
        {
            _id: '8',
            name: 'Petunia',
            category: 'Annual Plants',
            image: '/images/p8.jpg',
            price: 19.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Watermelon Hanging Basket'
        },
        {
            _id: '9',
            name: 'Fern',
            category: 'Garden Plants & Flowers',
            image: '/images/p9.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Boston Fern Hanging Basket'
        },
        {
            _id: '10',
            name: 'Arborvitae',
            category: 'Garden Plants & Flowers',
            image: '/images/p10.jpg',
            price: 119.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'Emerald Green, 5 ft'
        },
        {
            _id: '11',
            name: 'Strawberries',
            category: 'Garden Plants & Flowers',
            image: '/images/p11.jpg',
            price: 9.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '4.25 inches, edible'
        },
        {
            _id: '12',
            name: 'Lavendar',
            category: 'Garden Plants & Flowers',
            image: '/images/p12.jpg',
            price: 119.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: '#3 pot container'
        }, {
            _id: '13',
            name: 'Cherry Tomato',
            category: 'Garden Plants & Flowers',
            image: '/images/p13.jpg',
            price: 5.19,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'delightfully sweet'
        }, {
            _id: '14',
            name: 'Cucumber',
            category: 'Garden Plants & Flowers',
            image: '/images/p14.jpg',
            price: 5.19,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'crunchy pickling cucumbers'
        }, {
            _id: '15',
            name: 'Hydrangea',
            category: 'Garden Plants & Flowers',
            image: '/images/p15.jpg',
            price: 39.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'lace-cap hydrangea and has exceptionally rich, vibrant flowers'
        }, {
            _id: '16',
            name: 'Rose Bush',
            category: 'Garden Plants & Flowers',
            image: '/images/p16.jpg',
            price: 34.99,
            countInStock: 10,
            brand: 'Green Garden',
            rating: 5,
            numReviews: 10,
            description: 'soft orange blossoms from summer through fall. It is disease resistant and low maintenance.'
        },
    ],
};
export default data;